# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="I-E-A-I-A-I-O.mp3"
Content-Type: audio/mpeg

< ./I-E-A-I-A-I-O.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/a1af1a61-e947-4439-8f8e-2de855bbb83d/transcription
Content-Type: application/json

{
    "prompt": "musica , system of a down"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "a1af1a61-e947-4439-8f8e-2de855bbb83d",
    "temperature": 0.5,
    "prompt": "Gere um resumo da musica: '''{transcription}''' "
}